// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzKHtasxfMwwccp1iwPVpZg5YbDCFvjBc',
    appId: '1:426246823212:web:3c4c9e3cafda969712e089',
    messagingSenderId: '426246823212',
    projectId: 'chat-demo-372ed',
    authDomain: 'chat-demo-372ed.firebaseapp.com',
    databaseURL: 'https://chat-demo-372ed-default-rtdb.firebaseio.com',
    storageBucket: 'chat-demo-372ed.appspot.com',
    measurementId: 'G-6SXWVFD95W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNj84Kni5yE6jaZLXi3x-xId91J4U3rSo',
    appId: '1:426246823212:android:ddd7a0a6cacda4b512e089',
    messagingSenderId: '426246823212',
    projectId: 'chat-demo-372ed',
    databaseURL: 'https://chat-demo-372ed-default-rtdb.firebaseio.com',
    storageBucket: 'chat-demo-372ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu9mFs3TrXWx1MKUejkp0-oK-5SZzYy-M',
    appId: '1:426246823212:ios:b0f1bdf13eca4d6212e089',
    messagingSenderId: '426246823212',
    projectId: 'chat-demo-372ed',
    databaseURL: 'https://chat-demo-372ed-default-rtdb.firebaseio.com',
    storageBucket: 'chat-demo-372ed.appspot.com',
    androidClientId: '426246823212-7cma5e4iienlao2h4kipqchdl2sasbgj.apps.googleusercontent.com',
    iosClientId: '426246823212-nh1hfgnniahkjasak29snklj53imm41n.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatDemoFirebase',
  );
}
